on: [push, repository_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
            pip install aiohttp
            python build.py
        - uses: docker/login-action@master
          with:
              username: chaowenguo
              password: ${{secrets.DOCKER}}
        - uses: docker/setup-buildx-action@master        
        - uses: docker/build-push-action@master
          with:
              context: .
              push: true            
              tags: chaowenguo/vertx:latest
