on: [push, repository_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - uses: actions/setup-python@master
          with:
              python-version: '3.x'
        - run: |
            pip install gitpython
            python build.py
        - uses: akhileshns/heroku-deploy@v3.5.6
          with:
              heroku_api_key: ${{secrets.HEROKU}}
              heroku_app_name: vvertx
              heroku_email: chaowen.guo1@gmail.com
              usedocker: true
        - uses: docker/login-action@master
          with:
              username: chaowenguo
              password: ${{secrets.DOCKER}}
        - uses: docker/setup-buildx-action@master        
        - uses: docker/build-push-action@master
          with:
              push: true            
              tags: chaowenguo/vertx:latest
        #- run: |
        #     curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        #      ibmcloud cf install
        #      ibmcloud login -r us-south -g chaowenGuo --apikey ${{secrets.IBM}}
        #      ibmcloud target --cf-api api.us-south.cf.cloud.ibm.com  -o chaowen.guo1@gmail.com -s chaowenGuo
        #      ibmcloud cf push
        #      ibmcloud logout
