on: repository_dispatch
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git subtree pull --prefix=src/main/resources/static/ https://github.com/chaowenGUO/aiohttp master --squash       
          git push
