on: [push, repository_dispatch]
jobs:
    report:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
              python-version: '3.x'
        - run: |
            pip install gitpython
            python foo.py
        - uses: akhileshns/heroku-deploy@v3.2.6
          with:
              heroku_api_key: ${{secrets.HEROKU}}
              heroku_app_name: 'sspringboot'
              heroku_email: 'chaowen.guo1@gmail.com'
              usedocker: true
        - uses: redhat-developer/openshift-action@v2.1.0
          with:
              openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
              parameters: '{"apitoken": "${{ secrets.OPENSHIFT }}", "acceptUntrustedCerts": "true"}'
              cmd: | 
                  'get projects'
