on: [push, repository_dispatch]
jobs:
    report:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
              python-version: '3.x'
        - run: |
            pip install gitpython==3.1.3
            python foo.py
        - uses: akhileshns/heroku-deploy@v3.2.6
          with:
              heroku_api_key: ${{secrets.HEROKU}}
              heroku_app_name: sspringboot
              heroku_email: chaowen.guo1@gmail.com
              usedocker: true
        - uses: docker/build-push-action@v1.1.0
          with:
              username: chaowenguo
              password: ${{secrets.DOCKER}}
              repository: chaowenguo/springboot
              tags: latest
        - run: |
              curl -sL https://ibm.biz/idt-installer | bash
              ibmcloud login -r us-south -g chaowenGuo --cf-api api.us-south.cf.cloud.ibm.com -o chaowen.guo1@gmail.com -s chaowenGuo-u chaowen.guo1@gmail.com -p HL798820y+
              #ibmcloud cf push
  
