on: repository_dispatch
jobs:
    report:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
              python-version: '3.x' 
        - run: |
            pip install gitpython
            python foo.py
            cd src/main/resources/static
            git rm -rf .github/workflows Procfile *.txt *.py README.md
            git mv -f database.sql ..
            git commit --allow-empty-message -m ''
            git push
