on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
              python-version: '3.x'
        - env:
              TOKEN: ${{secrets.TOKEN}}
          run: |
              pip install aiohttp
              python foo.py
              git fetch --unshallow
              git remote set-url origin https://chaowen.guo1:KF1d8ff2zyvi7nbkUvTs@us-south.git.cloud.ibm.com/chaowen.guo1/aiohttp.git
              git push -u origin master -f
