on: repository_dispatch
jobs:
    report:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
              python-version: '3.x' 
        - run: |
            pip install gitpython
            python foo.py
            git commit --allow-empty-message -m ''
            git push
