on: repository_dispatch
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git merge -s ours --no-commit --allow-unrelated-histories https://github.com/chaowenGUO/aiohttp/master
          git read-tree --prefix=src/main/resources/static/ -u https://github.com/chaowenGUO/aiohttp/master    
          git push
